# Generated by Django 2.0.5 on 2018-05-29 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_auto_20180529_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
