# Generated by Django 2.0.5 on 2018-05-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20180529_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='result',
            name='quiz',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.DeleteModel(
            name='Result',
        ),
        migrations.AddField(
            model_name='scorerange',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_ranges', to='quiz.Quiz'),
        ),
    ]
