# Generated by Django 2.0.5 on 2018-06-11 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20180611_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredquestionspage',
            name='created',
            field=models.DateField(default=datetime.datetime(2018, 6, 11, 10, 35, 44, 687932, tzinfo=utc)),
        ),
    ]
