# Generated by Django 2.0.5 on 2018-06-11 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20180611_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredquestionspage',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
